<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
   
    <style>
        @page {
            header: page-header;
            footer: page-footer;
        }
        /* body{
            font-family:'nikosh_bangla', sans-serif;
        } */
        .collapse-table {
            border-collapse: collapse;
            width:100%;
        }
        td, th{
            padding:5px;
            vertical-align: top;
            border: 1px solid #dddddd;
        }
        
       
    </style>
</head>

<body>
    <htmlpageheader name="page-header" >
        <div style="text-align:center;">
            <h3 style="margin:0">Khwaja Yunus Ali Medical College & Hospital</h3>
            <p style="margin:0">FOUNDER: DR. M. M. AMJAD HUSSAIN</p>
            <hr>
        <p style="margin:0; text-decoration:underline;">{{ $title }}</p>
        </div>
    </htmlpageheader>

    <htmlpagefooter name="page-footer">
        <p style="text-align:center;">Report generated by - {{ auth()->user()->name }}. Time : {{ date('Y/m/d H:i A') }}</p> <br>
    </htmlpagefooter>


    <main style="word-wrap: break-word;">
        <table class="collapse-table">
            <tr>
                <th width="20px" >SL</th>
                <th >NAME</th>
                <th >HN</th>
                <th >AN</th>
                <th >DEPARTMENT</th>
                <th >DOCTOR</th>
            </tr>
            @foreach($documents as $row)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>{{ $row->name }}</td>
                    <td>{{ $row->hn }}</td>
                    <td>{{ $row->an }}</td>
                    <td>{{ $row->department->name }}</td>
                    <td>{{ $row->doctor->name }}</td>
                </tr>
            @endforeach
        </table>
    </main>

</body>


</html>